# -*- coding: utf-8 -*-
"""Projeto_Calculadora_Investimentos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BIN-1ep8yTg7mn-BtaDKa7qCD4ACqF54
"""

import pandas as pd
import numpy as np
import plotly.express as px
import math

print('Vamos calcular seu retorno anual de investimentos!')
print()

inv_inicial = float(input('Digite o investimento inicial (R$): '))
rend = float(input('Digite o rendimento anual (%): '))
calculo_anos = float(input('Digite a duração do investimento (anos): '))
i = 0
l1 = []
l2 = []
tabela = {}
soma = 0

print()
while i < calculo_anos:
  inv_inicial += inv_inicial * rend / 100
  i += 1
  l1.append(i)
  l2.append(round(inv_inicial, 0))
  tabela['Ano'] = l1
  tabela['Valor acumulado R$'] = l2

grafico = px.line(data_frame = tabela, x = 'Ano', y = 'Valor acumulado R$', 
                  title = 'Valores acumulados anualmente sob juros compostos')

grafico.show()